
package com.miw.uniovi.mapservice.astservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IApplicationServices", targetNamespace = "http://ws.chargerservice.asturias/application/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IApplicationServices {


    /**
     * 
     * @return
     *     returns com.miw.uniovi.mapservice.astservices.ArrayOfCargadorModel
     */
    @WebMethod(operationName = "GetCargadores", action = "http://ws.chargerservice.asturias/application/IApplicationServices/GetCargadores")
    @WebResult(name = "GetCargadoresResult", targetNamespace = "http://ws.chargerservice.asturias/application/")
    @RequestWrapper(localName = "GetCargadores", targetNamespace = "http://ws.chargerservice.asturias/application/", className = "com.miw.uniovi.mapservice.astservices.GetCargadores")
    @ResponseWrapper(localName = "GetCargadoresResponse", targetNamespace = "http://ws.chargerservice.asturias/application/", className = "com.miw.uniovi.mapservice.astservices.GetCargadoresResponse")
    @Action(input = "http://ws.chargerservice.asturias/application/IApplicationServices/GetCargadores", output = "http://ws.chargerservice.asturias/application/IApplicationServices/GetCargadoresResponse")
    public ArrayOfCargadorModel getCargadores();

}
